default:
  image: node:latest

test:
  stage: test
  before_script:
  - sudo apt-get update -qq && apt-get install -y -qq chromium-browser firefox
  - sudo ln -s /usr/lib/chromium-browser/chromium-browser /usr/bin/google-chrome
  - cd ./test/bin
  - wget "https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz"
  - tar -xvf *.tar.gz
  - mv gecko* ./test/bin/
  - wget "https://chromedriver.storage.googleapis.com/78.0.3904.70/chromedriver_linux64.zip"
  - unzip *.zip
  - mv chrome* ./test/bin/
  script:
  - npm install
  - node test.js
  only:
  - 31-implement-test-framework
  - staging
  - master

staging:
  stage: deploy
  script:
  - cp www public/staging
  artifacts:
    paths:
    - public
  only:
  - 31-implement-test-framework
  - staging

prod:
  stage: deploy
  script:
  - mv www public
  artifacts:
    paths:
    - public
  only:
  - master
