default:
  image: node:latest

test:
  stage: test
  before_script:
  - apt-get update -qq
  - apt-get install -qq -y chromium iceweasel
  #- /usr/bin/chromium --version
  - pushd .
  - mkdir -p ./test/bin && cd ./test/bin
  - wget "https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz" 2>&1 1>/dev/null
  #- wget "https://chromedriver.storage.googleapis.com/78.0.3904.70/chromedriver_linux64.zip" 2>&1 1>/dev/null
  - wget "https://chromedriver.storage.googleapis.com/73.0.3683.68/chromedriver_linux64.zip" 2>&1 1>/dev/null
  - tar -xvf *.tar.gz
  - unzip *.zip
  - popd
  - su node
  script:
  - npm install
  - node test.js
  only:
  - 31-implement-test-framework
  - staging
  - master

pages:
  stage: deploy
  script:
  - subdir="$CI_COMMIT_REF_SLUG"
  - if [ "$CI_COMMIT_REF_SLUG" == "$CI_DEFAULT_BRANCH" ]; then; subdir=""; fi;
  - mkdir -p public/$subdir
  - cp -r www public/$subdir
  artifacts:
    paths:
    - public
  only:
  - 31-implement-test-framework
  - staging
  - master
